apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workouts.fullname" . }}-api
  labels:
    {{- include "workouts.labels" . | nindent 4 }}
data:
  PUBLIC_URL: {{ .Values.api.publicUrl | quote }}
  UI_POLLING_INTERVAL_SECONDS: {{ .Values.api.publicConfig.pollingIntervalSeconds | quote }}
  MAP_FIT_PADDING_PIXELS: {{ .Values.api.publicConfig.mapFitPaddingPixels | quote }}
  BASE_MAP_TILE_URL: {{ .Values.api.publicConfig.baseMapTileUrl | quote }}
  BASE_MAP_ATTRIBUTION: {{ .Values.api.publicConfig.baseMapAttribution | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.otel.endpoint | quote }}
