{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "workouts.fullname" . }}
  labels: {{- include "workouts.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls: [{hosts: [{{ required "ingress.host is required" .Values.ingress.host }}], secretName: {{ required "ingress.tlsSecretName is required" .Values.ingress.tlsSecretName }}}]
  rules:
    - host: {{ required "ingress.host is required" .Values.ingress.host }}
      http:
        paths:
          {{- if .Values.ingress.mailpit.enabled }}
          - path: /mailpit
            pathType: Prefix
            backend: {service: {name: {{ include "workouts.fullname" . }}-mailpit-proxy, port: {name: http}}}
          {{- end }}
          - path: /api
            pathType: Prefix
            backend: {service: {name: {{ include "workouts.fullname" . }}-api, port: {name: http}}}
          - path: /swagger
            pathType: Prefix
            backend: {service: {name: {{ include "workouts.fullname" . }}-api, port: {name: http}}}
          - path: /
            pathType: Prefix
            backend: {service: {name: {{ include "workouts.fullname" . }}-ui, port: {name: http}}}
{{- end }}
