apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "workouts.fullname" . }}-pg-tileserv
  labels: {{- include "workouts.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: pg-tileserv}
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels: {app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: api}
      ports:
        - {protocol: TCP, port: 7800}
