apiVersion: v1
kind: Service
metadata:
  name: {{ include "workouts.fullname" . }}-ui
  labels: {{- include "workouts.labels" . | nindent 4 }}
spec:
  selector: {app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: ui}
  ports: [{name: http, port: 80, targetPort: http}]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workouts.fullname" . }}-pg-tileserv
  labels: {{- include "workouts.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: pg-tileserv}
  ports: [{name: http, port: 7800, targetPort: http}]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workouts.fullname" . }}-api
  labels: {{- include "workouts.labels" . | nindent 4 }}
spec:
  selector: {app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: api}
  ports: [{name: http, port: 80, targetPort: http}]
